### ISSUE TITLE
SystemPolicyDocumentsFolder does not work

### ISSUE THREAD

**Issue by shannon-pasto** [jamf/PPPC-Utility#30] opened 2019-10-22 02:54 UTC
Hi.

I am trying to set SystemPolicyDocumentsFolder to "allow" for an app but it doesn't appear to work as expected. SystemPolicyDownloadsFolder and SystemPolicyDesktopFolder work and when I view the policy in Jamf SystemPolicyDocumentsFolder doesn't appear to be listed, nor can I add it manually in the payload. If I save the file from the app the entry is there.

Thanks

**Comment by mm512** [comment] 2019-10-22 10:40
Hello @shannon-pasto,

_SystemPolicyDocumentsFolder_ is currently missing in the Jamf Pro. That's why you cannot see in on a list in a policy's payload.
The problem is already reported and should be fixed in the next version of the Jamf Pro.

**Closed by mm512** 2019-10-22 10:40 UTC
